---
inherit_from:
  - .rubocop_todo.yml
AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'db/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'spec/cassettes'
    - 'spec/factories/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
